[build]
  publish = "."

[[redirects]]
  from = "/passport"
  to = "/passport.html"
  status = 200

[[redirects]]
  from = "/badges"
  to = "/badges.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200
